[
  {
    id_association: 1,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 1,
    first_names: "Perla Marina",
    second_names: "Centeno",
    full_name: "Perla Marina Centeno",
    identification_number: "",
    birthdate: "",
    phone: "",
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 1,
    code_school: 15158,
    school_name: "San Francisco de Asís",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Subvencionado",
    id_grade: 1,
    grade: "1ro",
    id_section: 12,
    section: "B",
    address: "Detrás de la iglesia San José 200 mts al sur",
    town: "San José",
    municipality: "Diriamba",
    department: "Carazo",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 1,
    id_municipality: 1,
    is_active: true,
  },
  {
    id_association: 2,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 2,
    first_names: "María Gabriela",
    second_names: "Moraga Ortíz",
    full_name: "María Gabriela Moraga Ortíz",
    identification_number: "0421202920000U",
    birthdate: "1992-02-12",
    phone: 58287026,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 1,
    code_school: 15158,
    school_name: "San Francisco de Asís",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Subvencionado",
    id_grade: 1,
    grade: "1ro",
    id_section: 12,
    section: "B",
    address: "Detrás de la iglesia San José 200 mts al sur",
    town: "San José",
    municipality: "Diriamba",
    department: "Carazo",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 1,
    id_municipality: 1,
    is_active: true,
  },
  {
    id_association: 3,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 3,
    first_names: "Trixalia Susana",
    second_names: "Mercado López",
    full_name: "Trixalia Susana Mercado López",
    identification_number: "0421907750002M",
    birthdate: "1975-07-19",
    phone: 82013446,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 1,
    code_school: 15158,
    school_name: "San Francisco de Asís",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Subvencionado",
    id_grade: 5,
    grade: "5to",
    id_section: 11,
    section: "A",
    address: "Detrás de la iglesia San José 200 mts al sur",
    town: "San José",
    municipality: "Diriamba",
    department: "Carazo",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 1,
    id_municipality: 1,
    is_active: true,
  },
  {
    id_association: 4,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 4,
    first_names: "Isaac Neftali",
    second_names: "Acuña Aguilar",
    full_name: "Isaac Neftali Acuña Aguilar",
    identification_number: "0422804910003B",
    birthdate: "1991-04-28",
    phone: 85580509,
    email: "",
    gender: "M",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 1,
    code_school: 15158,
    school_name: "San Francisco de Asís",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Subvencionado",
    id_grade: 5,
    grade: "5to",
    id_section: 11,
    section: "A",
    address: "Detrás de la iglesia San José 200 mts al sur",
    town: "San José",
    municipality: "Diriamba",
    department: "Carazo",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 1,
    id_municipality: 1,
    is_active: true,
  },
  {
    id_association: 5,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 5,
    first_names: "Mirian del Carmen",
    second_names: "Ortíz Dávila",
    full_name: "Mirian del Carmen Ortíz Dávila",
    identification_number: "0420108760002Y",
    birthdate: "1976-08-01",
    phone: "",
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 1,
    code_school: 15158,
    school_name: "San Francisco de Asís",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Subvencionado",
    id_grade: 6,
    grade: "6to",
    id_section: 11,
    section: "A",
    address: "Detrás de la iglesia San José 200 mts al sur",
    town: "San José",
    municipality: "Diriamba",
    department: "Carazo",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 1,
    id_municipality: 1,
    is_active: true,
  },
  {
    id_association: 6,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 6,
    first_names: "Ana Natalia",
    second_names: "Ortíz Rodríguez",
    full_name: "Ana Natalia Ortíz Rodríguez",
    identification_number: "0420407880005M",
    birthdate: "1988-07-04",
    phone: 58024131,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 1,
    code_school: 15158,
    school_name: "San Francisco de Asís",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Subvencionado",
    id_grade: 2,
    grade: "2do",
    id_section: 11,
    section: "A",
    address: "Detrás de la iglesia San José 200 mts al sur",
    town: "San José",
    municipality: "Diriamba",
    department: "Carazo",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 1,
    id_municipality: 1,
    is_active: true,
  },
  {
    id_association: 7,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 7,
    first_names: "Carlos Javier",
    second_names: "Reyes García",
    full_name: "Carlos Javier Reyes García",
    identification_number: "03393824-0",
    birthdate: "",
    phone: 82013446,
    email: "",
    gender: "M",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 1,
    code_school: 15158,
    school_name: "San Francisco de Asís",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Subvencionado",
    id_grade: 4,
    grade: "4to",
    id_section: 11,
    section: "A",
    address: "Detrás de la iglesia San José 200 mts al sur",
    town: "San José",
    municipality: "Diriamba",
    department: "Carazo",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 1,
    id_municipality: 1,
    is_active: true,
  },
  {
    id_association: 8,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 8,
    first_names: "María Isabel",
    second_names: "Salinas",
    full_name: "María Isabel Salinas",
    identification_number: "0411302750004B",
    birthdate: "1975-02-13",
    phone: 76813012,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 1,
    code_school: 15158,
    school_name: "San Francisco de Asís",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Subvencionado",
    id_grade: 12,
    grade: "Multigrado",
    id_section: 15,
    section: "N/A",
    address: "Detrás de la iglesia San José 200 mts al sur",
    town: "San José",
    municipality: "Diriamba",
    department: "Carazo",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 1,
    id_municipality: 1,
    is_active: true,
  },
  {
    id_association: 9,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 9,
    first_names: "Liduvina del Carmen",
    second_names: "Lòpez Chavarría",
    full_name: "Liduvina del Carmen Lòpez Chavarría",
    identification_number: "4540112880003B",
    birthdate: "1988-12-01",
    phone: 82016343,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 2,
    code_school: 15353,
    school_name: "Enmanuel Mongalo",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Público",
    id_grade: 3,
    grade: "3ro",
    id_section: 11,
    section: "A",
    address: "Km. 58 1/2 carretera sur",
    town: "Monte Grande Occidental",
    municipality: "Santa Teresa",
    department: "Carazo",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 1,
    id_municipality: 2,
    is_active: true,
  },
  {
    id_association: 10,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 10,
    first_names: "Tania Nohemí",
    second_names: "Lara Hernández",
    full_name: "Tania Nohemí Lara Hernández",
    identification_number: "0442311960000Q",
    birthdate: "1996-11-23",
    phone: 84637051,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 2,
    code_school: 15353,
    school_name: "Enmanuel Mongalo",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Público",
    id_grade: 2,
    grade: "2do",
    id_section: 11,
    section: "A",
    address: "Km. 58 1/2 carretera sur",
    town: "Monte Grande Occidental",
    municipality: "Santa Teresa",
    department: "Carazo",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 1,
    id_municipality: 2,
    is_active: true,
  },
  {
    id_association: 11,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 11,
    first_names: "María del Carmen",
    second_names: "Centeno Solís",
    full_name: "María del Carmen Centeno Solís",
    identification_number: "0411612750000T",
    birthdate: "1975-12-16",
    phone: "",
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 2,
    code_school: 15353,
    school_name: "Enmanuel Mongalo",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Público",
    id_grade: 1,
    grade: "1ro",
    id_section: 11,
    section: "A",
    address: "Km. 58 1/2 carretera sur",
    town: "Monte Grande Occidental",
    municipality: "Santa Teresa",
    department: "Carazo",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 1,
    id_municipality: 2,
    is_active: true,
  },
  {
    id_association: 12,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 12,
    first_names: "Patricia de los Ángeles",
    second_names: "Mojica Lara",
    full_name: "Patricia de los Ángeles Mojica Lara",
    identification_number: "0442403870001Q",
    birthdate: "1987-03-24",
    phone: 82016343,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 2,
    code_school: 15353,
    school_name: "Enmanuel Mongalo",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Público",
    id_grade: 4,
    grade: "4to",
    id_section: 11,
    section: "A",
    address: "Km. 58 1/2 carretera sur",
    town: "Monte Grande Occidental",
    municipality: "Santa Teresa",
    department: "Carazo",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 1,
    id_municipality: 2,
    is_active: true,
  },
  {
    id_association: 13,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 13,
    first_names: "Pedro Antonio",
    second_names: "Salazar",
    full_name: "Pedro Antonio Salazar",
    identification_number: "0461504660000A",
    birthdate: "1966-04-15",
    phone: 83734744,
    email: "",
    gender: "M",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 2,
    code_school: 15353,
    school_name: "Enmanuel Mongalo",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Público",
    id_grade: 5,
    grade: "5to",
    id_section: 11,
    section: "A",
    address: "Km. 58 1/2 carretera sur",
    town: "Monte Grande Occidental",
    municipality: "Santa Teresa",
    department: "Carazo",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 1,
    id_municipality: 2,
    is_active: true,
  },
  {
    id_association: 14,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 14,
    first_names: "Rosa Marveli",
    second_names: "Arce Téllez",
    full_name: "Rosa Marveli Arce Téllez",
    identification_number: "0461801690000V",
    birthdate: "1969-01-18",
    phone: 56523601,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 2,
    code_school: 15353,
    school_name: "Enmanuel Mongalo",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Público",
    id_grade: 6,
    grade: "6to",
    id_section: 11,
    section: "A",
    address: "Km. 58 1/2 carretera sur",
    town: "Monte Grande Occidental",
    municipality: "Santa Teresa",
    department: "Carazo",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 1,
    id_municipality: 2,
    is_active: true,
  },
  {
    id_association: 15,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 15,
    first_names: "María Elena",
    second_names: "Ceas Rodríguez",
    full_name: "María Elena Ceas Rodríguez",
    identification_number: "0860211830005B",
    birthdate: "1983-11-02",
    phone: 76257466,
    email: "mariaelenazeas7@gmail.com",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 6,
    code_school: 27340,
    school_name: "El Peregrino",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Subvencionado",
    id_grade: 1,
    grade: "1ro",
    id_section: 11,
    section: "A",
    address: "Inst. Centro Catequistico 1 1/2 c. este",
    town: "El Calvario",
    municipality: "El Viejo",
    department: "Chinandega",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 2,
    id_municipality: 4,
    is_active: true,
  },
  {
    id_association: 16,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 16,
    first_names: "Dayssi Regina",
    second_names: "Tàborra Garrido",
    full_name: "Dayssi Regina Tàborra Garrido",
    identification_number: "0862512730002J",
    birthdate: "1973-12-25",
    phone: 86875105,
    email: "dtabora201@gmail.com",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 6,
    code_school: 27340,
    school_name: "El Peregrino",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Subvencionado",
    id_grade: 6,
    grade: "6to",
    id_section: 11,
    section: "A",
    address: "Inst. Centro Catequistico 1 1/2 c. este",
    town: "El Calvario",
    municipality: "El Viejo",
    department: "Chinandega",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 2,
    id_municipality: 4,
    is_active: true,
  },
  {
    id_association: 17,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 17,
    first_names: "Junieth Elizabeth",
    second_names: "Rodríguez Urbina",
    full_name: "Junieth Elizabeth Rodríguez Urbina",
    identification_number: "0862502900000Y",
    birthdate: "1990-02-25",
    phone: 83936147,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 6,
    code_school: 27340,
    school_name: "El Peregrino",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Subvencionado",
    id_grade: 3,
    grade: "3ro",
    id_section: 11,
    section: "A",
    address: "Inst. Centro Catequistico 1 1/2 c. este",
    town: "El Calvario",
    municipality: "El Viejo",
    department: "Chinandega",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 2,
    id_municipality: 4,
    is_active: true,
  },
  {
    id_association: 18,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 18,
    first_names: "Adriana Carolina",
    second_names: "Pichardo Romero",
    full_name: "Adriana Carolina Pichardo Romero",
    identification_number: "0861812920001P",
    birthdate: "1992-12-18",
    phone: 85084234,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 6,
    code_school: 27340,
    school_name: "El Peregrino",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Subvencionado",
    id_grade: 2,
    grade: "2do",
    id_section: 11,
    section: "A",
    address: "Inst. Centro Catequistico 1 1/2 c. este",
    town: "El Calvario",
    municipality: "El Viejo",
    department: "Chinandega",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 2,
    id_municipality: 4,
    is_active: true,
  },
  {
    id_association: 19,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 19,
    first_names: "Roxana",
    second_names: "Romero",
    full_name: "Roxana Romero",
    identification_number: "",
    birthdate: "",
    phone: "",
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 6,
    code_school: 27340,
    school_name: "El Peregrino",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Subvencionado",
    id_grade: 4,
    grade: "4to",
    id_section: 11,
    section: "A",
    address: "Inst. Centro Catequistico 1 1/2 c. este",
    town: "El Calvario",
    municipality: "El Viejo",
    department: "Chinandega",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 2,
    id_municipality: 4,
    is_active: true,
  },
  {
    id_association: 20,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 20,
    first_names: "Joseling Carina",
    second_names: "Balladares Medina",
    full_name: "Joseling Carina Balladares Medina",
    identification_number: "0810304970006V",
    birthdate: "1997-04-03",
    phone: 87697693,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 6,
    code_school: 27340,
    school_name: "El Peregrino",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Subvencionado",
    id_grade: 5,
    grade: "5to",
    id_section: 11,
    section: "A",
    address: "Inst. Centro Catequistico 1 1/2 c. este",
    town: "El Calvario",
    municipality: "El Viejo",
    department: "Chinandega",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 2,
    id_municipality: 4,
    is_active: true,
  },
  {
    id_association: 21,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 21,
    first_names: "Daniela Concepción",
    second_names: "Díaz Acevedo",
    full_name: "Daniela Concepción Díaz Acevedo",
    identification_number: "0852108890000S",
    birthdate: "1989-08-21",
    phone: 78006746,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 3,
    code_school: 12264,
    school_name: "Rey Juan Carlos I",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Privado",
    id_grade: 6,
    grade: "6to",
    id_section: 11,
    section: "A",
    address: "Proyecto Betania Reparto Monserrat Chinandega",
    town: "Reparto Monserrat",
    municipality: "Chinandega",
    department: "Chinandega",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 2,
    id_municipality: 3,
    is_active: true,
  },
  {
    id_association: 22,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 22,
    first_names: "Dominga Antonia Cáceres Gómez",
    second_names: "Cáceres Gómez",
    full_name: "Dominga Antonia Cáceres Gómez Cáceres Gómez",
    identification_number: "0871509910000K",
    birthdate: "1991-09-15",
    phone: 85744811,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 3,
    code_school: 12264,
    school_name: "Rey Juan Carlos I",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Privado",
    id_grade: 5,
    grade: "5to",
    id_section: 11,
    section: "A",
    address: "Proyecto Betania Reparto Monserrat Chinandega",
    town: "Reparto Monserrat",
    municipality: "Chinandega",
    department: "Chinandega",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 2,
    id_municipality: 3,
    is_active: true,
  },
  {
    id_association: 23,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 23,
    first_names: "Ingrid Karina",
    second_names: "Martínez Reyes",
    full_name: "Ingrid Karina Martínez Reyes",
    identification_number: "0810801880007M",
    birthdate: "1988-01-08",
    phone: 87848421,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 3,
    code_school: 12264,
    school_name: "Rey Juan Carlos I",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Privado",
    id_grade: 1,
    grade: "1ro",
    id_section: 11,
    section: "A",
    address: "Proyecto Betania Reparto Monserrat Chinandega",
    town: "Reparto Monserrat",
    municipality: "Chinandega",
    department: "Chinandega",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 2,
    id_municipality: 3,
    is_active: true,
  },
  {
    id_association: 24,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 24,
    first_names: "Gloría Esperanza",
    second_names: "Carrión Hernández",
    full_name: "Gloría Esperanza Carrión Hernández",
    identification_number: "0863005850003K",
    birthdate: "1985-05-30",
    phone: 78576958,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 3,
    code_school: 12264,
    school_name: "Rey Juan Carlos I",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Privado",
    id_grade: 2,
    grade: "2do",
    id_section: 11,
    section: "A",
    address: "Proyecto Betania Reparto Monserrat Chinandega",
    town: "Reparto Monserrat",
    municipality: "Chinandega",
    department: "Chinandega",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 2,
    id_municipality: 3,
    is_active: true,
  },
  {
    id_association: 25,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 25,
    first_names: "Ninoska Raquel",
    second_names: "Gutierrez Balladares",
    full_name: "Ninoska Raquel Gutierrez Balladares",
    identification_number: "0811910860008G",
    birthdate: "1986-10-19",
    phone: 75425000,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 3,
    code_school: 12264,
    school_name: "Rey Juan Carlos I",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Privado",
    id_grade: 3,
    grade: "3ro",
    id_section: 11,
    section: "A",
    address: "Proyecto Betania Reparto Monserrat Chinandega",
    town: "Reparto Monserrat",
    municipality: "Chinandega",
    department: "Chinandega",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 2,
    id_municipality: 3,
    is_active: true,
  },
  {
    id_association: 26,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 26,
    first_names: "Hazzel Deyanira",
    second_names: "López Méndez",
    full_name: "Hazzel Deyanira López Méndez",
    identification_number: "0862009900001K",
    birthdate: "1990-09-20",
    phone: 82427474,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 3,
    code_school: 12264,
    school_name: "Rey Juan Carlos I",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Privado",
    id_grade: 4,
    grade: "4to",
    id_section: 11,
    section: "A",
    address: "Proyecto Betania Reparto Monserrat Chinandega",
    town: "Reparto Monserrat",
    municipality: "Chinandega",
    department: "Chinandega",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 2,
    id_municipality: 3,
    is_active: true,
  },
  {
    id_association: 27,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 27,
    first_names: "Saira Yadira",
    second_names: "Maradiaga",
    full_name: "Saira Yadira Maradiaga",
    identification_number: "0860705770002C",
    birthdate: "1977-05-07",
    phone: 57498314,
    email: "Sairamaradi123@gmail.com",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 7,
    code_school: 11819,
    school_name: "Teresita González",
    school_type: "Multigrado",
    modality: "Matutino",
    dependency: "Público",
    id_grade: 12,
    grade: "Multigrado",
    id_section: 15,
    section: "N/A",
    address: "Km 13 Ruta Puerto Morazan",
    town: "Carlos Fonseca",
    municipality: "Puerto Morazán",
    department: "Chinandega",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 2,
    id_municipality: 5,
    is_active: true,
  },
  {
    id_association: 28,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 28,
    first_names: "Gloria Maribel",
    second_names: "Paz Vasquez",
    full_name: "Gloria Maribel Paz Vasquez",
    identification_number: "0861804810002X",
    birthdate: "1981-04-18",
    phone: 76351206,
    email: "pazgloria217@gmail.com",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 7,
    code_school: 11819,
    school_name: "Teresita González",
    school_type: "Multigrado",
    modality: "Matutino",
    dependency: "Público",
    id_grade: 12,
    grade: "Multigrado",
    id_section: 15,
    section: "N/A",
    address: "Km 13 Ruta Puerto Morazan",
    town: "Carlos Fonseca",
    municipality: "Puerto Morazán",
    department: "Chinandega",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 2,
    id_municipality: 5,
    is_active: true,
  },
  {
    id_association: 29,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 29,
    first_names: "Yaasy",
    second_names: "Ochoa",
    full_name: "Yaasy Ochoa",
    identification_number: "0862007810002w",
    birthdate: "1981-07-20",
    phone: 88330607,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 7,
    code_school: 11819,
    school_name: "Teresita González",
    school_type: "Multigrado",
    modality: "Matutino",
    dependency: "Público",
    id_grade: 2,
    grade: "2do",
    id_section: 11,
    section: "A",
    address: "Km 13 Ruta Puerto Morazan",
    town: "Carlos Fonseca",
    municipality: "Puerto Morazán",
    department: "Chinandega",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 2,
    id_municipality: 5,
    is_active: true,
  },
  {
    id_association: 30,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 30,
    first_names: "Reyna María",
    second_names: "Centeno",
    full_name: "Reyna María Centeno",
    identification_number: "0812311750010J",
    birthdate: "1975-11-23",
    phone: 81859787,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 4,
    code_school: 12171,
    school_name: "Hogar San José",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Público",
    id_grade: 12,
    grade: "Multigrado",
    id_section: 15,
    section: "N/A",
    address: "Contiguo al Centro Educacional Mantica Berio",
    town: "La Libertad",
    municipality: "Chinandega",
    department: "Chinandega",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 2,
    id_municipality: 3,
    is_active: true,
  },
  {
    id_association: 31,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 31,
    first_names: "Julia Bertha",
    second_names: "Juárez Reyes",
    full_name: "Julia Bertha Juárez Reyes",
    identification_number: "0811011760016G",
    birthdate: "1976-11-10",
    phone: "",
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 4,
    code_school: 12171,
    school_name: "Hogar San José",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Público",
    id_grade: 12,
    grade: "Multigrado",
    id_section: 15,
    section: "N/A",
    address: "Contiguo al Centro Educacional Mantica Berio",
    town: "La Libertad",
    municipality: "Chinandega",
    department: "Chinandega",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 2,
    id_municipality: 3,
    is_active: true,
  },
  {
    id_association: 32,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 32,
    first_names: "Florentina de los Àngeles",
    second_names: "Moreira Lira",
    full_name: "Florentina de los Àngeles Moreira Lira",
    identification_number: "2812701760009Y",
    birthdate: "1976-01-27",
    phone: 88673467,
    email: "florentinamoreiralira76@gmail.com",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 4,
    code_school: 12171,
    school_name: "Hogar San José",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Público",
    id_grade: 12,
    grade: "Multigrado",
    id_section: 15,
    section: "N/A",
    address: "Contiguo al Centro Educacional Mantica Berio",
    town: "La Libertad",
    municipality: "Chinandega",
    department: "Chinandega",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 2,
    id_municipality: 3,
    is_active: true,
  },
  {
    id_association: 33,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 33,
    first_names: "Fátima",
    second_names: "Ordoñez",
    full_name: "Fátima Ordoñez",
    identification_number: "0811603930001J",
    birthdate: "1993-03-16",
    phone: 84822629,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 4,
    code_school: 12171,
    school_name: "Hogar San José",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Público",
    id_grade: 12,
    grade: "Multigrado",
    id_section: 15,
    section: "N/A",
    address: "Contiguo al Centro Educacional Mantica Berio",
    town: "La Libertad",
    municipality: "Chinandega",
    department: "Chinandega",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 2,
    id_municipality: 3,
    is_active: true,
  },
  {
    id_association: 34,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 34,
    first_names: "Sorayda",
    second_names: "Núñez",
    full_name: "Sorayda Núñez",
    identification_number: "",
    birthdate: "",
    phone: "",
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 5,
    code_school: 27338,
    school_name: "Divino Niño",
    school_type: "Multigrado",
    modality: "Matutino",
    dependency: "Público",
    id_grade: 12,
    grade: "Multigrado",
    id_section: 15,
    section: "N/A",
    address: "De la parroquia el Divino Niño 1 c al oeste",
    town: "Colonia Divino Niño",
    municipality: "El Viejo",
    department: "Chinandega",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 2,
    id_municipality: 4,
    is_active: true,
  },
  {
    id_association: 35,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 35,
    first_names: "Anielka Juniethe",
    second_names: "López Campos",
    full_name: "Anielka Juniethe López Campos",
    identification_number: "0860506840005U",
    birthdate: "1984-06-05",
    phone: 82925766,
    email: "lopezanielka584lopez@gmail.com",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 5,
    code_school: 27338,
    school_name: "Divino Niño",
    school_type: "Multigrado",
    modality: "Matutino",
    dependency: "Público",
    id_grade: 12,
    grade: "Multigrado",
    id_section: 15,
    section: "N/A",
    address: "De la parroquia el Divino Niño 1 c al oeste",
    town: "Colonia Divino Niño",
    municipality: "El Viejo",
    department: "Chinandega",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 2,
    id_municipality: 4,
    is_active: true,
  },
  {
    id_association: 36,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 36,
    first_names: "Flanklin Javier",
    second_names: "Luna Pantoja",
    full_name: "Flanklin Javier Luna Pantoja",
    identification_number: "0812509940011X",
    birthdate: "1994-09-25",
    phone: 78764086,
    email: "",
    gender: "M",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 5,
    code_school: 27338,
    school_name: "Divino Niño",
    school_type: "Multigrado",
    modality: "Matutino",
    dependency: "Público",
    id_grade: 12,
    grade: "Multigrado",
    id_section: 15,
    section: "N/A",
    address: "De la parroquia el Divino Niño 1 c al oeste",
    town: "Colonia Divino Niño",
    municipality: "El Viejo",
    department: "Chinandega",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 2,
    id_municipality: 4,
    is_active: true,
  },
  {
    id_association: 37,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 37,
    first_names: "Gloria Del Socorro",
    second_names: "Bonilla",
    full_name: "Gloria Del Socorro Bonilla",
    identification_number: "1210203810003R",
    birthdate: "1981-03-02",
    phone: 84191723,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 12,
    code_school: 16764,
    school_name: "San Pablo",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Privado",
    id_grade: 1,
    grade: "1ro",
    id_section: 11,
    section: "A",
    address: "De la Texaco 5 c al oeste",
    town: "Felipe Acosta Zona # 4",
    municipality: "Juigalpa",
    department: "Chontales",
    region: "Central",
    country: "Nicaragua",
    id_country: 1,
    id_department: 3,
    id_municipality: 9,
    is_active: true,
  },
  {
    id_association: 38,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 38,
    first_names: "Ana Esther",
    second_names: "Ríos Zambrana",
    full_name: "Ana Esther Ríos Zambrana",
    identification_number: "1212601920006Y",
    birthdate: "1992-01-26",
    phone: 86965146,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 12,
    code_school: 16764,
    school_name: "San Pablo",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Privado",
    id_grade: 3,
    grade: "3ro",
    id_section: 11,
    section: "A",
    address: "De la Texaco 5 c al oeste",
    town: "Felipe Acosta Zona # 4",
    municipality: "Juigalpa",
    department: "Chontales",
    region: "Central",
    country: "Nicaragua",
    id_country: 1,
    id_department: 3,
    id_municipality: 9,
    is_active: true,
  },
  {
    id_association: 39,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 39,
    first_names: "Heyling Anielka",
    second_names: "García Zeledón",
    full_name: "Heyling Anielka García Zeledón",
    identification_number: "",
    birthdate: "",
    phone: 83307969,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 12,
    code_school: 16764,
    school_name: "San Pablo",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Privado",
    id_grade: 2,
    grade: "2do",
    id_section: 11,
    section: "A",
    address: "De la Texaco 5 c al oeste",
    town: "Felipe Acosta Zona # 4",
    municipality: "Juigalpa",
    department: "Chontales",
    region: "Central",
    country: "Nicaragua",
    id_country: 1,
    id_department: 3,
    id_municipality: 9,
    is_active: true,
  },
  {
    id_association: 40,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 40,
    first_names: "Silvia de los Angeles",
    second_names: "Suazo",
    full_name: "Silvia de los Angeles Suazo",
    identification_number: "1211405870000U",
    birthdate: "1987-05-14",
    phone: 83608293,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 12,
    code_school: 16764,
    school_name: "San Pablo",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Privado",
    id_grade: 2,
    grade: "2do",
    id_section: 12,
    section: "B",
    address: "De la Texaco 5 c al oeste",
    town: "Felipe Acosta Zona # 4",
    municipality: "Juigalpa",
    department: "Chontales",
    region: "Central",
    country: "Nicaragua",
    id_country: 1,
    id_department: 3,
    id_municipality: 9,
    is_active: true,
  },
  {
    id_association: 41,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 41,
    first_names: "Marvin Antonio",
    second_names: "Tercero Tinoco",
    full_name: "Marvin Antonio Tercero Tinoco",
    identification_number: "1211411770007V",
    birthdate: "1977-11-14",
    phone: 78556011,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 12,
    code_school: 16764,
    school_name: "San Pablo",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Privado",
    id_grade: 3,
    grade: "3ro",
    id_section: 12,
    section: "B",
    address: "De la Texaco 5 c al oeste",
    town: "Felipe Acosta Zona # 4",
    municipality: "Juigalpa",
    department: "Chontales",
    region: "Central",
    country: "Nicaragua",
    id_country: 1,
    id_department: 3,
    id_municipality: 9,
    is_active: true,
  },
  {
    id_association: 42,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 42,
    first_names: "Kenia Nayara",
    second_names: "Barreda Gonzalez",
    full_name: "Kenia Nayara Barreda Gonzalez",
    identification_number: "1210705001004T",
    birthdate: "1900-05-07",
    phone: 86378464,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 12,
    code_school: 16764,
    school_name: "San Pablo",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Privado",
    id_grade: 3,
    grade: "3ro",
    id_section: 12,
    section: "B",
    address: "De la Texaco 5 c al oeste",
    town: "Felipe Acosta Zona # 4",
    municipality: "Juigalpa",
    department: "Chontales",
    region: "Central",
    country: "Nicaragua",
    id_country: 1,
    id_department: 3,
    id_municipality: 9,
    is_active: true,
  },
  {
    id_association: 43,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 43,
    first_names: "Glenda Judith",
    second_names: "Flores García",
    full_name: "Glenda Judith Flores García",
    identification_number: "1212611991002J",
    birthdate: "1999-11-26",
    phone: 58755891,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 12,
    code_school: 16764,
    school_name: "San Pablo",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Privado",
    id_grade: 4,
    grade: "4to",
    id_section: 12,
    section: "B",
    address: "De la Texaco 5 c al oeste",
    town: "Felipe Acosta Zona # 4",
    municipality: "Juigalpa",
    department: "Chontales",
    region: "Central",
    country: "Nicaragua",
    id_country: 1,
    id_department: 3,
    id_municipality: 9,
    is_active: true,
  },
  {
    id_association: 44,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 44,
    first_names: "Alba Lisseth",
    second_names: "Sequeira Espinoza",
    full_name: "Alba Lisseth Sequeira Espinoza",
    identification_number: "1270407820002U",
    birthdate: "1982-07-04",
    phone: 86996550,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 12,
    code_school: 16764,
    school_name: "San Pablo",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Privado",
    id_grade: 4,
    grade: "4to",
    id_section: 11,
    section: "A",
    address: "De la Texaco 5 c al oeste",
    town: "Felipe Acosta Zona # 4",
    municipality: "Juigalpa",
    department: "Chontales",
    region: "Central",
    country: "Nicaragua",
    id_country: 1,
    id_department: 3,
    id_municipality: 9,
    is_active: true,
  },
  {
    id_association: 45,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 45,
    first_names: "Jairo Antonio",
    second_names: "Robleto Robleto",
    full_name: "Jairo Antonio Robleto Robleto",
    identification_number: "1212301820007X",
    birthdate: "1982-01-23",
    phone: 85265457,
    email: "",
    gender: "M",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 12,
    code_school: 16764,
    school_name: "San Pablo",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Privado",
    id_grade: 5,
    grade: "5to",
    id_section: 11,
    section: "A",
    address: "De la Texaco 5 c al oeste",
    town: "Felipe Acosta Zona # 4",
    municipality: "Juigalpa",
    department: "Chontales",
    region: "Central",
    country: "Nicaragua",
    id_country: 1,
    id_department: 3,
    id_municipality: 9,
    is_active: true,
  },
  {
    id_association: 46,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 46,
    first_names: "Karla Karina",
    second_names: "Muñoz",
    full_name: "Karla Karina Muñoz",
    identification_number: "1210310810000L",
    birthdate: "1981-10-03",
    phone: 86051795,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 12,
    code_school: 16764,
    school_name: "San Pablo",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Privado",
    id_grade: 6,
    grade: "6to",
    id_section: 11,
    section: "A",
    address: "De la Texaco 5 c al oeste",
    town: "Felipe Acosta Zona # 4",
    municipality: "Juigalpa",
    department: "Chontales",
    region: "Central",
    country: "Nicaragua",
    id_country: 1,
    id_department: 3,
    id_municipality: 9,
    is_active: true,
  },
  {
    id_association: 47,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 47,
    first_names: "Ana Sofía",
    second_names: "Díaz Álvarez",
    full_name: "Ana Sofía Díaz Álvarez",
    identification_number: "1260201950001M",
    birthdate: "1995-01-02",
    phone: 88287701,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 13,
    code_school: 17814,
    school_name: "Hermida Flores Gutiérrez",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Público",
    id_grade: 2,
    grade: "2do",
    id_section: 11,
    section: "A",
    address: "Salida a Santo Domingo",
    town: "La Libertad",
    municipality: "La Libertad",
    department: "Chontales",
    region: "Central",
    country: "Nicaragua",
    id_country: 1,
    id_department: 3,
    id_municipality: 10,
    is_active: true,
  },
  {
    id_association: 48,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 48,
    first_names: "Mariely María",
    second_names: "Jirón Oporta",
    full_name: "Mariely María Jirón Oporta",
    identification_number: "1212206870000T",
    birthdate: "1987-06-22",
    phone: 57060230,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 13,
    code_school: 17814,
    school_name: "Hermida Flores Gutiérrez",
    school_type: "Regular",
    modality: "Matutino",
    dependency: "Público",
    id_grade: 1,
    grade: "1ro",
    id_section: 11,
    section: "A",
    address: "Salida a Santo Domingo",
    town: "La Libertad",
    municipality: "La Libertad",
    department: "Chontales",
    region: "Central",
    country: "Nicaragua",
    id_country: 1,
    id_department: 3,
    id_municipality: 10,
    is_active: true,
  },
  {
    id_association: 49,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 49,
    first_names: "María Modesta",
    second_names: "Fernández",
    full_name: "María Modesta Fernández",
    identification_number: "1261506800001E",
    birthdate: "1980-06-15",
    phone: 84936648,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 14,
    code_school: 18147,
    school_name: "San Marcos",
    school_type: "Multigrado",
    modality: "Matutino",
    dependency: "Público",
    id_grade: 3,
    grade: "3ro",
    id_section: 11,
    section: "A",
    address: "Comarca San Francisco del Gamalote, Carretera a Bertulia",
    town: "San Fracisco del Gamalote",
    municipality: "La Libertad",
    department: "Chontales",
    region: "Central",
    country: "Nicaragua",
    id_country: 1,
    id_department: 3,
    id_municipality: 10,
    is_active: true,
  },
  {
    id_association: 50,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 50,
    first_names: "María Anyela",
    second_names: "Dávila Urbina",
    full_name: "María Anyela Dávila Urbina",
    identification_number: "3651201820000K",
    birthdate: "1982-01-12",
    phone: 81785901,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 14,
    code_school: 18147,
    school_name: "San Marcos",
    school_type: "Multigrado",
    modality: "Matutino",
    dependency: "Público",
    id_grade: 12,
    grade: "Multigrado",
    id_section: 15,
    section: "N/A",
    address: "Comarca San Francisco del Gamalote, Carretera a Bertulia",
    town: "San Fracisco del Gamalote",
    municipality: "La Libertad",
    department: "Chontales",
    region: "Central",
    country: "Nicaragua",
    id_country: 1,
    id_department: 3,
    id_municipality: 10,
    is_active: true,
  },
  {
    id_association: 51,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 51,
    first_names: "Izayda Paulina",
    second_names: "Dávila Dávila",
    full_name: "Izayda Paulina Dávila Dávila",
    identification_number: "1260310940001D",
    birthdate: "1994-10-03",
    phone: 78451039,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 14,
    code_school: 18147,
    school_name: "San Marcos",
    school_type: "Multigrado",
    modality: "Matutino",
    dependency: "Público",
    id_grade: 12,
    grade: "Multigrado",
    id_section: 15,
    section: "N/A",
    address: "Comarca San Francisco del Gamalote, Carretera a Bertulia",
    town: "San Fracisco del Gamalote",
    municipality: "La Libertad",
    department: "Chontales",
    region: "Central",
    country: "Nicaragua",
    id_country: 1,
    id_department: 3,
    id_municipality: 10,
    is_active: true,
  },
  {
    id_association: 52,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 52,
    first_names: "Esperanza",
    second_names: "Flores",
    full_name: "Esperanza Flores",
    identification_number: "",
    birthdate: "",
    phone: "",
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 10,
    code_school: 17225,
    school_name: "Las Alturas",
    school_type: "Multigrado",
    modality: "Matutino",
    dependency: "Público",
    id_grade: 12,
    grade: "Multigrado",
    id_section: 15,
    section: "N/A",
    address: "Del Km 153 carretera al rama 14 km al lago",
    town: "La Altura",
    municipality: "Acoyapa",
    department: "Chontales",
    region: "Central",
    country: "Nicaragua",
    id_country: 1,
    id_department: 3,
    id_municipality: 8,
    is_active: true,
  },
  {
    id_association: 53,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 53,
    first_names: "Danys Alexander",
    second_names: "Flores Aguilar",
    full_name: "Danys Alexander Flores Aguilar",
    identification_number: "1210724910000J",
    birthdate: "1991-24-07",
    phone: 84355119,
    email: "",
    gender: "M",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 10,
    code_school: 17225,
    school_name: "Las Alturas",
    school_type: "Multigrado",
    modality: "Matutino",
    dependency: "Público",
    id_grade: 12,
    grade: "Multigrado",
    id_section: 15,
    section: "N/A",
    address: "Del Km 153 carretera al rama 14 km al lago",
    town: "La Altura",
    municipality: "Acoyapa",
    department: "Chontales",
    region: "Central",
    country: "Nicaragua",
    id_country: 1,
    id_department: 3,
    id_municipality: 8,
    is_active: true,
  },
  {
    id_association: 54,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 54,
    first_names: "Amy Halima",
    second_names: "López Briceño",
    full_name: "Amy Halima López Briceño",
    identification_number: "2012710880006X",
    birthdate: "1988-10-27",
    phone: 89350570,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 16,
    code_school: 15452,
    school_name: "Colegio Diocesano Inmaculada Concepción",
    school_type: "Regular",
    modality: "Doble Turno",
    dependency: "Privado",
    id_grade: 2,
    grade: "2do",
    id_section: 11,
    section: "A",
    address: "De las oficinas de catedral 2 c. al sur",
    town: "Calle Morazán",
    municipality: "Granada",
    department: "Granada",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 4,
    id_municipality: 11,
    is_active: true,
  },
  {
    id_association: 55,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 55,
    first_names: "Reyna Isabel",
    second_names: "Obando Espinoza",
    full_name: "Reyna Isabel Obando Espinoza",
    identification_number: "2010101850010D",
    birthdate: "1985-01-01",
    phone: 88712592,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 16,
    code_school: 15452,
    school_name: "Colegio Diocesano Inmaculada Concepción",
    school_type: "Regular",
    modality: "Doble Turno",
    dependency: "Privado",
    id_grade: 1,
    grade: "1ro",
    id_section: 11,
    section: "A",
    address: "De las oficinas de catedral 2 c. al sur",
    town: "Calle Morazán",
    municipality: "Granada",
    department: "Granada",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 4,
    id_municipality: 11,
    is_active: true,
  },
  {
    id_association: 56,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 56,
    first_names: "Meyling de Fátima",
    second_names: "Ortíz Estrada",
    full_name: "Meyling de Fátima Ortíz Estrada",
    identification_number: "4011205900007B",
    birthdate: "1990-05-12",
    phone: 87046987,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 16,
    code_school: 15452,
    school_name: "Colegio Diocesano Inmaculada Concepción",
    school_type: "Regular",
    modality: "Doble Turno",
    dependency: "Privado",
    id_grade: 4,
    grade: "4to",
    id_section: 11,
    section: "A",
    address: "De las oficinas de catedral 2 c. al sur",
    town: "Calle Morazán",
    municipality: "Granada",
    department: "Granada",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 4,
    id_municipality: 11,
    is_active: true,
  },
  {
    id_association: 57,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 57,
    first_names: "Ana Margarita",
    second_names: "Lezcano",
    full_name: "Ana Margarita Lezcano",
    identification_number: "2011307880004V",
    birthdate: "1988-07-13",
    phone: 81505999,
    email: "",
    gender: "F",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 16,
    code_school: 15452,
    school_name: "Colegio Diocesano Inmaculada Concepción",
    school_type: "Regular",
    modality: "Doble Turno",
    dependency: "Privado",
    id_grade: 3,
    grade: "3ro",
    id_section: 11,
    section: "A",
    address: "De las oficinas de catedral 2 c. al sur",
    town: "Calle Morazán",
    municipality: "Granada",
    department: "Granada",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 4,
    id_municipality: 11,
    is_active: true,
  },
  {
    id_association: 58,
    id_user_type: 1,
    user_type: "Docente",
    id_user: 58,
    first_names: "Gabriel Antonio",
    second_names: "Martínez Alemán",
    full_name: "Gabriel Antonio Martínez Alemán",
    identification_number: "5691508880000C",
    birthdate: "1988-08-15",
    phone: 82703729,
    email: "",
    gender: "M",
    id_laptop: 1,
    serial: "N/A",
    uuid: "",
    laptop_type: "N/A",
    id_school: 16,
    code_school: 15452,
    school_name: "Colegio Diocesano Inmaculada Concepción",
    school_type: "Regular",
    modality: "Doble Turno",
    dependency: "Privado",
    id_grade: 5,
    grade: "5to",
    id_section: 11,
    section: "A",
    address: "De las oficinas de catedral 2 c. al sur",
    town: "Calle Morazán",
    municipality: "Granada",
    department: "Granada",
    region: "Pacifico",
    country: "Nicaragua",
    id_country: 1,
    id_department: 4,
    id_municipality: 11,
    is_active: true,
  },
];
